version: 2
updates:
  # Updates integration tests project and all dependencies, which means the whole application
  - package-ecosystem: "nuget"
    directory: "/tests/Web.IntegrationsTests/"
    schedule:
      interval: "weekly"
    groups:
      update-project-and-integration-tests:
        patterns:
          - "*"
  # Updates the unit tests project
  - package-ecosystem: "nuget"
    directory: "/tests/Domain.UnitTests/"
    schedule:
      interval: "weekly"
    groups:
      update-unit-tests:
        patterns:
          - "*"
