version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Application/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/Domain/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/Infrastructure/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/Web/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/Domain.UnitTests/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/Web.IntegrationsTests/"
    schedule:
      interval: "weekly"
