@Web_HostAddress = https://localhost:7078

GET {{Web_HostAddress}}/api/todoitems

###

POST {{Web_HostAddress}}/api/todoitems
Content-Type: application/json

{
  //CreateTodoItemCommand
}

###

GET {{Web_HostAddress}}/api/todoitems/0

###

DELETE {{Web_HostAddress}}/api/todoitems/0

###

PUT {{Web_HostAddress}}/api/todoitems/0
Content-Type: application/json

{
  //UpdateTodoItemRequestDto
}

###
