name: Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to NuGet.org

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/InmetaTrondheim/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: dotnet build
    - uses: nuget/setup-nuget@v1
      name: Setup NuGet
      with:
        nuget-version: '6.x'
    - name: Create the package
      run: nuget pack InmetaTemplate.nuspec -NoDefaultExcludes
    - name: Publish the package to GPR
      run: dotnet nuget push *.nupkg